[build]
  functions = "api"
  publish = "public"

[[redirects]]
  from = "/api/ws/*"
  to = "/.netlify/functions/websocket"
  status = 200
  force = true
  [redirects.headers]
    Upgrade = "websocket"
    Connection = "upgrade"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["ws"]

[dev]
  framework = "#static"
  port = 8888

[build.environment]
  NODE_VERSION = "18.14.0"