[build]
  functions = "api"
  publish = "public"

[[redirects]]
  from = "/api/ws/*"
  to = "/.netlify/functions/websocket"
  status = 200
  force = true

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["ws"]

[dev]
  framework = "#static"
  port = 4000
  targetPort = 8888
  staticServerPort = 8888

[build.environment]
  NODE_VERSION = "18.14.0"